# Standard-library imports
from uuid import UUID, uuid4

# Third-party imports
from fastapi import FastAPI, HTTPException, Path
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from slowapi import Limiter
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware
from slowapi.util import get_remote_address
from starlette.requests import Request
from starlette.responses import JSONResponse

# Local imports
from ai_service import create_client, generate_reply
from config import ALLOWED_ORIGINS
from conversation_manager import ConversationManager
from logger import get_logger


logger = get_logger(__name__)

limiter = Limiter(
    key_func=get_remote_address,
)


app = FastAPI(
    title="Quantheonix AI Chatbot API",
    summary="AI-powered website assistant backend",
    description=(
        "The backend API for the Quantheonix AI Website Assistant.\n\n"
        "## Main features\n"
        "- Send messages to the AI chatbot\n"
        "- Maintain separate conversation sessions\n"
        "- Reset existing conversations\n"
        "- View active conversation statistics\n"
        "- Check application health"
    ),
    version="0.2.0",
    contact={
        "name": "Quantheonix",
        "email": "madhukaaththanayaka@gmail.com",
    },
)

app.state.limiter = limiter
app.add_middleware(SlowAPIMiddleware)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "DELETE"],
    allow_headers=["Content-Type", "Authorization"],
)

client = create_client()
conversation_manager = ConversationManager(
    client,
    expiry_minutes=30,
    )


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The message sent by the user.",
        examples=[
            "Hello, what services does Quantheonix provide?"
        ],
    )

    conversation_id: UUID | None = Field(
        default=None,
        description=(
            "Existing conversation ID. "
            "Send null to begin a new conversation."
        ),
        examples=[
            "f021de92-ffa8-43df-8a08-c7e9e6ab0e5c"
        ],
    )


class ChatResponse(BaseModel):
    conversation_id: UUID = Field(
        description="The ID used to continue this conversation.",
        examples=["f021de92-ffa8-43df-8a08-c7e9e6ab0e5c"],
    )

    reply: str = Field(
        description="The response generated by the AI assistant.",
        examples=[
            "Hello! Quantheonix develops AI, robotics, and XR projects."
        ],
    )


class ResetConversationResponse(BaseModel):
    message: str = Field(
        description="The result of the reset operation.",
        examples=["Conversation reset successfully."],
    )


class ConversationStatsResponse(BaseModel):
    active_conversations: int = Field(
        description="Number of conversations currently stored in memory.",
        examples=[3],
    )

@app.exception_handler(RateLimitExceeded)
async def rate_limit_handler(
    request: Request,
    exception: RateLimitExceeded,
) -> JSONResponse:
    logger.warning(
        "Rate limit exceeded for client %s",
        request.client.host if request.client else "unknown",
    )

    return JSONResponse(
        status_code=429,
        content={
            "detail": (
                "Too many requests. "
                "Please wait before trying again."
            )
        },
    )

@app.get(
    "/",
    tags=["System"],
    summary="API welcome message",
    description="Confirms that the Quantheonix chatbot API is running.",
    response_description="A welcome message from the API.",
)
def root() -> dict[str, str]:
    return {
        "message": "Quantheonix AI Chatbot API is running."
    }

@app.get(
    "/health",
    tags=["System"],
    summary="Check API health",
    description=(
        "Checks whether the FastAPI application is running normally."
    ),
    response_description="The current health status of the API.",
)
def health_check() -> dict[str, str]:
    return {
        "status": "healthy"
    }

@app.get(
    "/api/conversations/stats",
    response_model=ConversationStatsResponse,
    tags=["Conversations"],
    summary="Get active conversation count",
    description=(
        "Removes expired conversations and returns the number of "
        "conversations currently stored in server memory."
    ),
    response_description="The current number of active conversations.",
)
def conversation_stats() -> ConversationStatsResponse:
    active_count = (
        conversation_manager.get_active_conversation_count()
    )

    return ConversationStatsResponse(
        active_conversations=active_count,
    )


@app.post(
    "/api/chat",
    response_model=ChatResponse,
    tags=["Chat"],
    summary="Send a message to the chatbot",
    description=(
        "Sends a user message to the Quantheonix AI assistant.\n\n"
        "- Send `conversation_id` as `null` to start a new chat.\n"
        "- Reuse the returned `conversation_id` to continue the same chat.\n"
        "- The message must contain between 1 and 2000 characters."
    ),
    response_description=(
        "The generated AI reply and the conversation ID."
    ),
    responses={
        400: {
            "description": "The message is empty after whitespace removal."
        },
        422: {
            "description": "The submitted request failed validation."
        },
        429: {
            "description": "The AI API quota has been reached."
        },
        500: {
            "description": "The chatbot failed to generate a response."
        },
    },
)
@limiter.limit("10/minute")
def chat_endpoint(
    request: Request,
    payload: ChatRequest,
) -> ChatResponse:
    try:
        user_message = payload.message.strip()

        if not user_message:
            raise HTTPException(
                status_code=400,
                detail="Message cannot be empty.",
            )

        conversation_id = payload.conversation_id or uuid4()

        logger.info(
            "Processing chat request for conversation %s",
            conversation_id,
        )

        chat = conversation_manager.get_chat(
            str(conversation_id)
        )

        reply = generate_reply(chat, user_message)

        logger.info(
            "Chat response generated for conversation %s",
            conversation_id,
        )

        return ChatResponse(
            conversation_id=conversation_id,
            reply=reply,
        )

    except HTTPException:
        raise

    except Exception as error:
        error_message = str(error)

        logger.exception(
            "Chat endpoint failed for conversation %s",
            payload.conversation_id,
        )

        if "429" in error_message or "RESOURCE_EXHAUSTED" in error_message:
            raise HTTPException(
                status_code=429,
                detail=(
                    "The chatbot has reached its current API quota. "
                    "Please try again later."
                ),
            ) from error

        raise HTTPException(
            status_code=500,
            detail="The chatbot could not generate a response.",
        ) from error

        raise HTTPException(
            status_code=500,
            detail="The chatbot could not generate a response.",
        ) from error


@app.delete(
    "/api/conversations/{conversation_id}",
    response_model=ResetConversationResponse,
    tags=["Conversations"],
    summary="Reset a conversation",
    description=(
        "Removes the selected conversation from temporary server memory. "
        "Sending another message with the same ID will create a fresh "
        "Gemini chat session."
    ),
    response_description="The result of the conversation reset operation.",
    responses={
        422: {
            "description": "The conversation ID is not a valid UUID."
        },
    },
)
def reset_conversation(
    conversation_id: UUID = Path
    (
        ...,
        description="The UUID of the conversation to reset.",
        examples=["f021de92-ffa8-43df-8a08-c7e9e6ab0e5c"],
    )
) -> ResetConversationResponse:
    was_removed = conversation_manager.remove_chat(
        str(conversation_id)
    )

    if was_removed:
        logger.info(
            "Conversation %s was reset",
            conversation_id,
        )

        return ResetConversationResponse(
            message="Conversation reset successfully.",
        )

    return ResetConversationResponse(
        message="Conversation did not exist or had already expired.",
    )