"""add public widget conversations

Revision ID: 38bad5d04c1d
Revises: 838e263e7088
Create Date: 2026-08-20 15:08:37.704002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '38bad5d04c1d'
down_revision: Union[str, Sequence[str], None] = '838e263e7088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_conversations',
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_public_conversations_assistant_id_assistants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_conversations'))
    )
    op.create_index(op.f('ix_public_conversations_assistant_id'), 'public_conversations', ['assistant_id'], unique=False)
    op.create_table('public_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', 'system', name='message_role', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['public_conversations.id'], name=op.f('fk_public_messages_conversation_id_public_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_messages'))
    )
    op.create_index(op.f('ix_public_messages_conversation_id'), 'public_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_messages_conversation_id'), table_name='public_messages')
    op.drop_table('public_messages')
    op.drop_index(op.f('ix_public_conversations_assistant_id'), table_name='public_conversations')
    op.drop_table('public_conversations')
    # ### end Alembic commands ###
