"""add assistant documents

Revision ID: aab00bd1845c
Revises: 38bad5d04c1d
Create Date: 2026-08-28 09:27:59.394196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab00bd1845c'
down_revision: Union[str, Sequence[str], None] = '38bad5d04c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_documents',
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_assistant_documents_assistant_id_assistants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_documents'))
    )
    op.create_index(op.f('ix_assistant_documents_assistant_id'), 'assistant_documents', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_assistant_documents_status'), 'assistant_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_documents_status'), table_name='assistant_documents')
    op.drop_index(op.f('ix_assistant_documents_assistant_id'), table_name='assistant_documents')
    op.drop_table('assistant_documents')
    # ### end Alembic commands ###
